# Generated by Django 2.1.14 on 2019-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(choices=[('KEY_SSP_LANDSCAPE', '広告タグ: 横長'), ('KEY_SSP_POST', '広告タグ: 投稿'), ('KEY_SSP_GA_TAG', 'GAタグ'), ('KEY_OGP_IMAGE_URL', 'OGP画像URL')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(),
        ),
    ]
