# Generated by Django 2.1.14 on 2019-12-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191220_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagraminfo',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('CAROUSEL_ALBUM', 'CAROUSEL_ALBUM')], max_length=100, verbose_name='Type'),
        ),
    ]
