# Generated by Django 2.1.14 on 2020-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191220_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='身長'),
            preserve_default=False,
        ),
    ]
