# Generated by Django 2.1.14 on 2020-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200108_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubetoken',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='youtubetoken',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='youtubetoken',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='youtubetoken',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='youtubeinfo',
            name='chanel_id',
            field=models.CharField(default='', max_length=100, verbose_name='チャネルID'),
            preserve_default=False,
        ),
    ]
