# Generated by Django 2.1.14 on 2020-01-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200111_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='非公開ページ'),
        ),
    ]
