# Generated by Django 2.1.14 on 2020-02-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200111_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ssp_landscape',
            field=models.TextField(blank=True, null=True, verbose_name='SSP(縦長)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ssp_post',
            field=models.TextField(blank=True, null=True, verbose_name='SSP(投稿)'),
        ),
    ]
