# Generated by Django 2.1.14 on 2020-02-21 20:04

import django.core.validators
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200209_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image1',
            field=models.FileField(blank=True, null=True, upload_to=web.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image2',
            field=models.FileField(blank=True, null=True, upload_to=web.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image3',
            field=models.FileField(blank=True, null=True, upload_to=web.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='プロフィール画像'),
        ),
    ]
