# Generated by Django 2.1.14 on 2020-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200222_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wikipidia_desc',
            field=models.CharField(blank=True, max_length=400, verbose_name='活動エリア'),
        ),
    ]
